"""add_delivery_fields

Revision ID: 7ae4744e1aaf
Revises: 
Create Date: 2026-01-25 14:02:40.444680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae4744e1aaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('order_number', sa.String(length=50), nullable=True))
    op.add_column('deliveries', sa.Column('delivery_address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'delivery_address')
    op.drop_column('deliveries', 'order_number')
    # ### end Alembic commands ###
