"""add_delivery_fields

Revision ID: 7ae4744e1aaf
Revises: 
Create Date: 2026-01-25 14:02:40.444680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


revision: str = '7ae4744e1aaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(conn, table: str, column: str) -> bool:
    if conn.dialect.name == "sqlite":
        r = conn.execute(text(f"PRAGMA table_info({table})"))
        return any(row[1] == column for row in r)
    return False


def upgrade() -> None:
    conn = op.get_bind()
    if not _has_column(conn, "deliveries", "order_number"):
        op.add_column('deliveries', sa.Column('order_number', sa.String(length=50), nullable=True))
    if not _has_column(conn, "deliveries", "delivery_address"):
        op.add_column('deliveries', sa.Column('delivery_address', sa.String(length=500), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'delivery_address')
    op.drop_column('deliveries', 'order_number')
    # ### end Alembic commands ###
